config/routes.rb
NflTeamsTracker::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root :to => "home#index"

  get "/:id" => "users#show", as: "user"
  get "/leagues/:id/join" => "leagues#join", as: "join_league"
  get "/leagues/:id/weeks" => "weeks#index", as: "league_weeks"
  get "/leagues/:id/parse" => "leagues#parse"

  resources :scores

  resources :users

  resources :leagues do
    resources :comments
    resources :weeks do
      member do
        resource :weekly_actives
      end
    end
    member do
      resource :picks
    end
  end

end

app/models/week.rb
class Week < ActiveRecord::Base
  default_scope order('num ASC')

  class << self
    def create_season(year)
      beginning_of_season = DateTime.parse('04/09/2014 04:00')
      (1..17).each do |n|
        Week.create(num: n, season: year, end_of_week: (beginning_of_season + (n.weeks)))
      end
    end
  end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController

  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
    else
      @user = current_user
    end
  end

  def show
    @user = User.find_by_id(params[:user_id]) || current_user
    @starters = @user.starters(params[:league_id], params[:id])
    @bench = @user.bench(params[:league_id], params[:id])
    @user_picks = @user.find_picks(params[:league_id])
  end

  def edit
    @current_user_picks = current_user.find_picks(params[:league_id])
    @home_team_ids = Array.new
    @away_team_ids = Array.new
    Schedule.find_all_by_week_id(League.find_active_week_id).each do |s|
      @home_team_ids << s.home_team_id
      @away_team_ids << s.away_team_id
    end
  end
end

app/views/weeks/_lineup.html.haml
- weekly_actives = WeeklyActive.league_week(current_league, week_id).map{|w| w.team.id}

%table.match_ups
  %tr
    %th
    %th Away
    %th 
    %th Home
    %th
  - week_games.each do |game|
    - if weekly_actives.include?(game.away_team.id) || weekly_actives.include?(game.home_team.id)
      %tr
        %td
          - if game.away_team.picks.map{|p| p.users_league_id}.include?(users_league.id)
            = game.away_team.week_results(week_id)
        %td
          = game.away_team.full_name
        %td @
        %td
          = game.home_team.full_name
        %td
          - if game.home_team.picks.map{|p| p.users_league_id}.include?(users_league.id)
            = game.home_team.week_results(week_id)

app/views/weeks/_start_or_bench.html.haml
%span{:class => ("locked" if p.team.this_week_locked?(League.find_active_week_id) )}
  - if p.started?(League.find_active_week_id)
    = link_to "Starting", league_weekly_actives_path(weekly_active: p.weekly_active(League.find_active_week_id)), method: :delete, class: "starting"
  - else
    = link_to "On Bench", new_league_weekly_actives_path(params[:league_id], League.find_active_week_id, pick_id: p.id, user_id: current_user.id), class: "benched"

app/views/weeks/edit.html.haml
= link_to "Back", league_week_path(params[:league_id], params[:id])
%h2 Your teams
%table
  %tr
    %th Away
    %th 
    %th Home
    - @current_user_picks.each do |p|
      %tr
        - if @away_team_ids.include?(p.team.id)
          %td
            = p.team.name
            = render :partial => 'start_or_bench', locals: {p: p}
          %td @
          %td.opponent
            = p.team.this_weeks_opponent(League.find_active_week_id).name
        -elsif @home_team_ids.include?(p.team.id)
          %td.opponent
            = p.team.this_weeks_opponent(League.find_active_week_id).name
          %td @
          %td
            = p.team.name
            = render :partial => 'start_or_bench', locals: {p: p}
        -else
          %td= p.team.name
          %td
          %td BYE

app/views/weeks/index.html.haml
= render :partial => 'weeks/lineup', locals: { week_games: Schedule.find_all_by_week_id(Week.find_by_num(2)), users_league: UsersLeague.find_by_user_id_and_league_id(current_user.id, current_league.id), week_id: 2 }

%h2 Weeks
%table
  %tr
    %th Week number
    %th Starters
  - Week.all.each do |week|
    -if active_week >= week.num
      %tr
        %td
          -if params[:user_id]
            = link_to "Week #{week.num}", league_week_path(params[:id], week.num, user_id: params[:user_id])
          -else
            = link_to "Week #{week.num}", league_week_path(params[:id], week.num)
        %td
          = @user.starters(params[:id], week.num).count

app/views/weeks/show.html.haml
%h1= "Week #{params[:id]}"
- if !params[:user_id] && params[:id].to_i == League.find_active_week
  = link_to "Edit lineup", edit_league_week_path(params[:league_id], params[:id])
%h2 Starters
%ul.unstyled
  - @starters.each do |s|
    %li= s.team.name
%h2 Bench
%ul.unstyled
  - @bench.each do |b|
    %li= b.team.name