config/routes.rb
NflTeamsTracker::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root :to => "home#index"

  get "/:id" => "users#show", as: "user"
  get "/leagues/:id/join" => "leagues#join", as: "join_league"
  get "/leagues/:id/weeks" => "weeks#index", as: "league_weeks"
  get "/leagues/:id/parse" => "leagues#parse"

  resources :scores

  resources :users

  resources :leagues do
    resources :comments
    resources :weeks do
      member do
        resource :weekly_actives
      end
    end
    member do
      resource :picks
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :leagues_attributes

  validates_presence_of :first_name, :last_name

  has_many :teams, :through => :picks
  has_many :users_leagues, :dependent => :destroy
  has_many :leagues, :through => :users_leagues

  accepts_nested_attributes_for :leagues

  def find_teams(league_id)
    ul = UsersLeague.find_by_user_id_and_league_id(self.id, league_id)
    ul.picks.map{|p| Team.find(p.team_id)} if ul.picks
  end

  def find_picks(league_id)
    UsersLeague.find_by_user_id_and_league_id(self.id, league_id).picks
  end

  def starters(league_id, week_id)
    WeeklyActive.find_all_by_user_id_and_league_id_and_week_id(self.id, league_id, week_id).map{|w| w.pick}
  end

  def bench(league_id, week_id)
    bench = find_picks(league_id).map{|p| p.id} - starters(league_id, week_id).map{|s| s.id}
    Pick.find(bench)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    session[:current_league_id] = nil
    @all_leagues = League.all
    @current_user_leagues = current_user.leagues
    @all_teams_names = Team.all.each.map{|t| "#{t.city} #{t.name}"}
  end
end

app/views/users/show.html.haml
- if user_signed_in?
  %h2 Leagues

  - if @current_user_leagues.present?
    %h3 Your leagues
    %table
      %tr
        %th League name
        %th Rank
      - @current_user_leagues.each do |league|
        %tr
          %td
            = link_to league.name, league_path(league)
          %td
            = (UsersLeague.find_by_user_id_and_league_id(current_user.id, league.id).current_rank + 1)
            of
            = league.users.count
  %h3 All leagues
  %table
    %tr
      %th League name
      %th # players
      %th
    - @all_leagues.each do |league|
      %tr
        %td= league.name
        %td= league.users.count
        %td
          -if @current_user_leagues.include?(league)
            = "Joined"
          -elsif league.users.count == 6 || league.name == "2012 Season"
            Full
          -else
            = link_to "Join", join_league_path(league)
  
- else
  = link_to 'Sign up', new_user_registration_path
  = link_to 'Login', new_user_session_path

/ = link_to "Parse", "#", class: "parse_espn"


%ul.placeholder.unstyled