config/routes.rb
NflTeamsTracker::Application.routes.draw do
  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}

  root :to => "home#index"

  get "/:id" => "users#show", as: "user"
  get "/leagues/:id/join" => "leagues#join", as: "join_league"
  get "/leagues/:id/weeks" => "weeks#index", as: "league_weeks"
  get "/leagues/:id/parse" => "leagues#parse"

  resources :scores

  resources :users

  resources :leagues do
    resources :comments
    resources :weeks do
      member do
        resource :weekly_actives
      end
    end
    member do
      resource :picks
    end
  end

end

app/views/shared/_header.html.haml
.container#headerArea
  .left
    %h3.logo= link_to "FFB LITE", root_path
  %ul.nav-bar.right
    -if current_league
      %li.active
        = link_to league_path(current_league), style: "cursor: auto" do
          League:
          %span.league_name= current_league.name
    / %li.has-flyout
    /   %a{:href => "#"} Nav Item 2
    /   %a.flyout-toggle{:href => "#"}
    /     %span     
    /   %ul.flyout{:style => "display: none; "}
    /     %li
    /       %a{:href => "#"} Sub Nav Item 1
    /     %li
    /       %a{:href => "#"} Sub Nav Item 2
    /     %li
    /       %a{:href => "#"} Sub Nav 3
    /     %li
    /       %a{:href => "#"} Sub Nav 4
    /     %li
    /       %a{:href => "#"} Sub Nav Item 5
    - if current_league
      %li.has-flyout
        %a{:href => "#"}= "Current Week: #{active_week}"
        %a.flyout-toggle{:href => "#"}
          %span     
        %div.flyout{:style => "display: none; color: #222"}
          %h5 Current Starters:
          -if current_starters.present?
            - current_starters.each do |s|
              %p= s.team.name
          -else
            None - click edit lineup
          %hr{style: "margin: 0 0 20px"}
          %p{style:"font-weight: 800"}= link_to "Edit lineup", edit_league_week_path(current_league, active_week)
          %p= link_to "View Previous Weeks", league_weeks_path(current_league)
    - if current_user
      %li.has-flyout
        %a{:href => "#"}
          - if user_signed_in?
            = current_user.email

        %a.flyout-toggle{:href => "#"}
          %span
        %ul.flyout{:style => "display: none; "}
          -if current_league 
            %li
              = link_to 'Add/Remove Teams', edit_picks_path(session[:current_league_id])
          %li
            = link_to 'Edit Profile', edit_user_registration_path
          %li
            = link_to 'Log out', destroy_user_session_path, method: :delete